# Generated by Django 4.1.2 on 2022-11-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juguete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=50)),
                ('nombre', models.TextField(max_length=50)),
                ('precio', models.IntegerField()),
                ('disponibilidad', models.TextField(max_length=2)),
                ('origen', models.TextField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('tipo', models.TextField(max_length=50)),
                ('marca', models.TextField(max_length=50)),
            ],
        ),
    ]
