# Generated by Django 4.1.2 on 2022-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juguetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguete',
            name='codigo',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
